<a href="https://colab.research.google.com/github/Sundess/Nepal-mental-health/blob/main/6_Final_Group_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Necessary Libraries & Dataset

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Regression Model
from sklearn.linear_model import LogisticRegression

# Classification Model
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestClassifier

# Neural Network
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix


from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import plotly.express as px
from google.colab import drive
import plotly.graph_objects as go


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Define the file path for the dataset
file_path = "/content/drive/MyDrive/Data Analysis and Machine Learning/Mental_health_dataset.csv"

# Read the dataset into a Pandas DataFrame
df = pd.read_csv(file_path)


# Data Pre Processing

In [ ]:
df.shape

(2625, 18)

In [ ]:
# Display basic information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2625 entries, 0 to 2624
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   S.N                 2625 non-null   int64  
 1   District_Name       2625 non-null   object 
 2   Zone                2625 non-null   object 
 3   Ecological_Belt     2625 non-null   object 
 4   Development_Region  2625 non-null   object 
 5   Year_BS             2625 non-null   int64  
 6   Year_AD             2625 non-null   int64  
 7   condition           2625 non-null   object 
 8   type                2625 non-null   object 
 9   Male                2625 non-null   int64  
 10  Female              2625 non-null   int64  
 11  Age                 2625 non-null   int64  
 12  Married             2625 non-null   int64  
 13  Unmarried           2625 non-null   int64  
 14  Education           2625 non-null   object 
 15  Employment          2625 non-null   object 
 16  lat   

In [ ]:
# Renaming selected columns to make them uniform
df.rename(columns={'condition': 'Condition', 'type': 'Type', 'lat': 'Latitude', 'long': 'Longitude'}, inplace=True)

In [ ]:
df.head()

S.N District_Name   Zone Ecological_Belt Development_Region  Year_BS  \
0    0     Taplejung  Mechi        Mountain            Eastern     2069   
1    1     Taplejung  Mechi        Mountain            Eastern     2069   
2    2     Taplejung  Mechi        Mountain            Eastern     2069   
3    3     Taplejung  Mechi        Mountain            Eastern     2069   
4    4     Taplejung  Mechi        Mountain            Eastern     2069   

   Year_AD Condition                            Type  Male  Female  Age  \
0     2012    Severe                      Dipression    26      24   19   
1     2012    Severe                       Psychosis    53      30   50   
2     2012     Major              Anxiety (Neurosis)    24      32   21   
3     2012     Major              Mental retardation    48      46   20   
4     2012     Major  Conversive disorder (Hysteria)    49      29   60   

   Married  Unmarried                                          Education  \
0       27         23  Some College, short continuing education or eq...   
1       57         26                                               None   
2       37         19                                              #####   
3       51         43                   College degree, bachelor, master   
4       45         33                                              #####   

  Employment   Latitude  Longitude  
0         no  27.618589  87.856661  
1        yes  27.618589  87.856661  
2        yes  27.618589  87.856661  
3        yes  27.618589  87.856661  
4    retired  27.618589  87.856661

In [ ]:
df.tail()

S.N District_Name      Zone Ecological_Belt Development_Region  \
2620  2620      Darchula  Mahakali        Mountain        Far-Western   
2621  2621      Darchula  Mahakali        Mountain        Far-Western   
2622  2622      Darchula  Mahakali        Mountain        Far-Western   
2623  2623      Darchula  Mahakali        Mountain        Far-Western   
2624  2624      Darchula  Mahakali        Mountain        Far-Western   

      Year_BS  Year_AD Condition                            Type  Male  \
2620     2077     2020     Minor              Anxiety (Neurosis)    47   
2621     2077     2020    Severe              Mental retardation    18   
2622     2077     2020    Severe  Conversive disorder (Hysteria)    27   
2623     2077     2020    Normal                      Alcoholism    55   
2624     2077     2020    Normal                         Epilesy    39   

      Female  Age  Married  Unmarried                         Education  \
2620      41   53       47         41  College degree, bachelor, master   
2621      22   38       24         16  College degree, bachelor, master   
2622      30   18        5         52          Up to 12 years of school   
2623      36   60       33         58  College degree, bachelor, master   
2624      30   24       48         21  College degree, bachelor, master   

     Employment   Latitude  Longitude  
2620        yes  29.892711  80.741361  
2621         no  29.892711  80.741361  
2622         no  29.892711  80.741361  
2623      #####  29.892711  80.741361  
2624        yes  29.892711  80.741361

In [ ]:
df.describe()

S.N      Year_BS      Year_AD         Male       Female  \
count  2625.000000  2625.000000  2625.000000  2625.000000  2625.000000   
mean   1312.000000  2071.862857  2014.862857    39.217143    38.765333   
std     757.916552     2.568618     2.568618    12.639741    12.423508   
min       0.000000  2069.000000  2012.000000    18.000000    18.000000   
25%     656.000000  2070.000000  2013.000000    28.000000    28.000000   
50%    1312.000000  2071.000000  2014.000000    39.000000    38.000000   
75%    1968.000000  2074.000000  2017.000000    51.000000    50.000000   
max    2624.000000  2077.000000  2020.000000    60.000000    60.000000   

               Age      Married    Unmarried     Latitude    Longitude  
count  2625.000000  2625.000000  2625.000000  2625.000000  2625.000000  
mean     38.762286    37.357333    40.625143    28.003789    84.254905  
std      12.513433    13.006108    21.568092     0.885817     2.170864  
min      18.000000     1.000000    -6.000000    26.571975    80.382090  
25%      28.000000    27.000000    25.000000    27.218320    82.359404  
50%      39.000000    38.000000    40.000000    27.948879    84.235742  
75%      50.000000    48.000000    55.000000    28.692376    86.007220  
max      60.000000    60.000000   108.000000    30.035133    87.955321

In [ ]:
print(df.dtypes)

S.N                     int64
District_Name          object
Zone                   object
Ecological_Belt        object
Development_Region     object
Year_BS                 int64
Year_AD                 int64
Condition              object
Type                   object
Male                    int64
Female                  int64
Age                     int64
Married                 int64
Unmarried               int64
Education              object
Employment             object
Latitude              float64
Longitude             float64
dtype: object


In [ ]:
# Dropping Unnecessary Columns
columns_to_drop = ['S.N', 'Year_BS', 'Education']
df = df.drop(columns=columns_to_drop)

In [ ]:
# Select specific columns of interest
selected_columns = ['District_Name', 'Condition', 'Employment', 'Type']

# Get unique values in each selected column
unique_values_dict = {col: df[col].unique() for col in selected_columns}

# Display the unique values for each selected column
for col, unique_values in unique_values_dict.items():
    print(f'Unique values in the {col} column:')
    print(unique_values)
    print()

Unique values in the District_Name column:
['Taplejung' 'Panchthar' 'Ilam' 'Jhapa' 'Morang' 'Sunsari' 'Dhankuta'
 'Teharthum' 'Sankhuwasabha' 'Bhojpur' 'Solukhumbu' 'Okhaldhunga'
 'Khotang' 'Udaypur' 'Saptari' 'Siraha' 'Dhanusha' 'Mahottari' 'Sarlahi'
 'Sindhuli' 'Ramechhap' 'Dolkha' 'Sindhupalchowk' 'Kavre' 'Lalitpur'
 'Bhaktapur' 'Kathmandu' 'Nuwakot' 'Rasuwa' 'Dhading' 'Makawanpur'
 'Rautahat' 'Bara' 'Parsa' 'Chitwan' 'Gorkha' 'Lamjung' 'Tanahu' 'Syangja'
 'Kaski' 'Manang' 'Mustang' 'Myagdi' 'Parbat' 'Baglung' 'Gulmi' 'Palpa'
 'Nawalparasi' 'Rupandehi' 'Kapilvastu' 'Arghakhanchi' 'Pyuthan' 'Rolpa'
 'Rukum' 'Salyan' 'Dang' 'Banke' 'Bardiya' 'Surkhet' 'Dailekh' 'Jajarkot'
 'Dolpa' 'Jumla' 'Kalikot' 'Mugu' 'Humla' 'Bajura' 'Bajhang' 'Achham'
 'Doti' 'Kailali' 'Kanchanpur' 'Dadeldhura' 'Baitadi' 'Darchula']

Unique values in the Condition column:
['Severe' 'Major' 'Normal' 'Minor']

Unique values in the Employment column:
['no' 'yes' 'retired' '####' '######' '#######' '#####']

Unique 

In [ ]:
# Checking Null values count
null_values=df.isnull().sum()
print(null_values)

District_Name         0
Zone                  0
Ecological_Belt       0
Development_Region    0
Year_AD               0
Condition             0
Type                  0
Male                  0
Female                0
Age                   0
Married               0
Unmarried             0
Employment            0
Latitude              0
Longitude             0
dtype: int64


In [ ]:
# Count duplicate rows (considering all columns)
duplicate_counts = df.duplicated().sum()

# Print the duplicate count
print("Number of duplicate rows:", duplicate_counts)

Number of duplicate rows: 0


In [ ]:
corrections = {
    'Dipression': 'Depression',
    'Anxiety (Neurosis)': 'Anxiety',
    'Epilesy': 'Epilepsy'
    # Add more corrections as needed
}

df['Type'] = df['Type'].replace(corrections)

# Display the updated values
print(df['Type'].unique())


['Depression' 'Psychosis' 'Anxiety' 'Mental retardation'
 'Conversive disorder (Hysteria)' 'Alcoholism' 'Epilepsy']


## Handling Missing or Unrealistic Values

In [ ]:
# Filter rows where 'Unmarried' is less than 0
filtered_df = df[df['Unmarried'] < 0]

# Print the filtered dataframe
filtered_df

District_Name         Zone Ecological_Belt Development_Region  Year_AD  \
37         Sunsari         Kosi           Terai            Eastern     2012   
97         Udaypur   Sagarmatha            Hill            Eastern     2012   
822         Myagdi  Dhawalagiri            Hill            Western     2013   
1159        Siraha   Sagarmatha           Terai            Eastern     2014   
1612       Sunsari         Kosi           Terai            Eastern     2015   
1672       Udaypur   Sagarmatha            Hill            Eastern     2015   
2397        Myagdi  Dhawalagiri            Hill            Western     2019   

     Condition                            Type  Male  Female  Age  Married  \
37      Normal                         Anxiety    29      18   41       49   
97       Major                        Epilepsy    22      26   38       54   
822      Minor              Mental retardation    24      28   47       55   
1159    Severe  Conversive disorder (Hysteria)    24      22   38       48   
1612    Normal                         Anxiety    29      18   41       49   
1672     Major                        Epilepsy    22      26   38       54   
2397     Minor              Mental retardation    24      28   47       55   

      Unmarried Employment   Latitude  Longitude  
37           -2        yes  26.683536  87.181275  
97           -6         no  26.897062  86.624308  
822          -3        yes  28.528774  83.475356  
1159         -2      #####  26.685278  86.326516  
1612         -2        yes  26.683536  87.181275  
1672         -6         no  26.897062  86.624308  
2397         -3        yes  28.528774  83.475356

In [ ]:
df = df.drop(df[df['Unmarried'] < 0].index) # Dropping filtered data

In [ ]:
employment_counts = df['Employment'].value_counts()

# Display the number of occurrences for each unique value in the 'Employment' column
print("Number of occurrences for each unique value in the 'Employment' column:")
print(employment_counts)
df.shape

Number of occurrences for each unique value in the 'Employment' column:
no         1393
yes         815
######      208
#####        75
retired      51
####         39
#######      37
Name: Employment, dtype: int64


(2618, 15)

In [ ]:
#Replacing the # valus from Employment Column
df['Employment'].replace(to_replace=r'.*#.*', value=np.nan, regex=True, inplace=True)
df

District_Name      Zone Ecological_Belt Development_Region  Year_AD  \
0        Taplejung     Mechi        Mountain            Eastern     2012   
1        Taplejung     Mechi        Mountain            Eastern     2012   
2        Taplejung     Mechi        Mountain            Eastern     2012   
3        Taplejung     Mechi        Mountain            Eastern     2012   
4        Taplejung     Mechi        Mountain            Eastern     2012   
...            ...       ...             ...                ...      ...   
2620      Darchula  Mahakali        Mountain        Far-Western     2020   
2621      Darchula  Mahakali        Mountain        Far-Western     2020   
2622      Darchula  Mahakali        Mountain        Far-Western     2020   
2623      Darchula  Mahakali        Mountain        Far-Western     2020   
2624      Darchula  Mahakali        Mountain        Far-Western     2020   

     Condition                            Type  Male  Female  Age  Married  \
0       Severe                      Depression    26      24   19       27   
1       Severe                       Psychosis    53      30   50       57   
2        Major                         Anxiety    24      32   21       37   
3        Major              Mental retardation    48      46   20       51   
4        Major  Conversive disorder (Hysteria)    49      29   60       45   
...        ...                             ...   ...     ...  ...      ...   
2620     Minor                         Anxiety    47      41   53       47   
2621    Severe              Mental retardation    18      22   38       24   
2622    Severe  Conversive disorder (Hysteria)    27      30   18        5   
2623    Normal                      Alcoholism    55      36   60       33   
2624    Normal                        Epilepsy    39      30   24       48   

      Unmarried Employment   Latitude  Longitude  
0            23         no  27.618589  87.856661  
1            26        yes  27.618589  87.856661  
2            19        yes  27.618589  87.856661  
3            43        yes  27.618589  87.856661  
4            33    retired  27.618589  87.856661  
...         ...        ...        ...        ...  
2620         41        yes  29.892711  80.741361  
2621         16         no  29.892711  80.741361  
2622         52         no  29.892711  80.741361  
2623         58        NaN  29.892711  80.741361  
2624         21        yes  29.892711  80.741361  

[2618 rows x 15 columns]

In [ ]:
#Checking to weather the values has been dropped or not.

# Count occurrences of each unique value in the 'Employment' column
employment_value_counts = df['Employment'].value_counts()

# Print the value counts
print("Value counts in the 'Employment' column:")
print(employment_value_counts)


Value counts in the 'Employment' column:
no         1393
yes         815
retired      51
Name: Employment, dtype: int64


In [ ]:
df.dropna(inplace=True)

In [ ]:
#Since marrige age in nepal is 20, and if average is less than 20 while total married is grater than unmarried the data is not good.

filtered_age = df[(df['Age'] < 20) & (df['Married'] > df['Unmarried'])]
print('Rows where age is less than 19 but number of married is greater than unmarried')
filtered_age.count()

Rows where age is less than 19 but number of married is greater than unmarried


District_Name         35
Zone                  35
Ecological_Belt       35
Development_Region    35
Year_AD               35
Condition             35
Type                  35
Male                  35
Female                35
Age                   35
Married               35
Unmarried             35
Employment            35
Latitude              35
Longitude             35
dtype: int64

In [ ]:
df.drop(filtered_age.index, inplace=True)

In [ ]:
df.head(15)

District_Name   Zone Ecological_Belt Development_Region  Year_AD Condition  \
1      Taplejung  Mechi        Mountain            Eastern     2012    Severe   
2      Taplejung  Mechi        Mountain            Eastern     2012     Major   
3      Taplejung  Mechi        Mountain            Eastern     2012     Major   
4      Taplejung  Mechi        Mountain            Eastern     2012     Major   
5      Taplejung  Mechi        Mountain            Eastern     2012    Severe   
6      Taplejung  Mechi        Mountain            Eastern     2012     Major   
7      Panchthar  Mechi            Hill            Eastern     2012    Normal   
8      Panchthar  Mechi            Hill            Eastern     2012    Severe   
9      Panchthar  Mechi            Hill            Eastern     2012    Severe   
10     Panchthar  Mechi            Hill            Eastern     2012    Severe   
11     Panchthar  Mechi            Hill            Eastern     2012     Major   
12     Panchthar  Mechi            Hill            Eastern     2012     Minor   
13     Panchthar  Mechi            Hill            Eastern     2012    Severe   
14          Ilam  Mechi            Hill            Eastern     2012     Minor   
15          Ilam  Mechi            Hill            Eastern     2012    Normal   

                              Type  Male  Female  Age  Married  Unmarried  \
1                        Psychosis    53      30   50       57         26   
2                          Anxiety    24      32   21       37         19   
3               Mental retardation    48      46   20       51         43   
4   Conversive disorder (Hysteria)    49      29   60       45         33   
5                       Alcoholism    30      20   27       49          1   
6                         Epilepsy    54      25   28       24         55   
7                       Depression    54      49   58       23         80   
8                        Psychosis    54      37   37       22         69   
9                          Anxiety    59      26   59       53         32   
10              Mental retardation    27      54   28       26         55   
11  Conversive disorder (Hysteria)    27      37   59       48         16   
12                      Alcoholism    54      21   29       19         56   
13                        Epilepsy    35      49   29       51         33   
14                      Depression    54      44   47       19         79   
15                       Psychosis    38      23   22       53          8   

   Employment   Latitude  Longitude  
1         yes  27.618589  87.856661  
2         yes  27.618589  87.856661  
3         yes  27.618589  87.856661  
4     retired  27.618589  87.856661  
5         yes  27.618589  87.856661  
6         yes  27.618589  87.856661  
7         yes  27.059531  87.820004  
8         yes  27.059531  87.820004  
9         yes  27.059531  87.820004  
10        yes  27.059531  87.820004  
11    retired  27.059531  87.820004  
12        yes  27.059531  87.820004  
13        yes  27.059531  87.820004  
14        yes  26.856045  87.945208  
15        yes  26.856045  87.945208

In [ ]:
print('Total data types and its value counts')
df["Type"].value_counts()

Total data types and its value counts


Depression                        322
Mental retardation                321
Psychosis                         317
Alcoholism                        317
Epilepsy                          317
Anxiety                           316
Conversive disorder (Hysteria)    314
Name: Type, dtype: int64

# Data Visulization

### Pie-chart Percentage Distribution of Mental Health Type

In [ ]:
# Pie chart for the percentage distribution of mental health types
fig = px.pie(df, names='Type', title='Percentage Distribution of Mental Health Types')
fig.show()

### Geographic Data Distribution

In [ ]:
#Visualization
# Create a scatter mapbox plot for latitude and longitude
fig = px.scatter_mapbox(
    df,
    lat='Latitude',
    lon='Longitude',
    title='Geographic Distribution of Data',
    mapbox_style='carto-positron',  # You can choose other map styles
    zoom=5,  # Adjust the initial zoom level
)

fig.show()




### Box Plot for Numeric Columns

In [ ]:
# Column to exlude of box plot
columns_to_exclude = ['Year_AD','Latitude', 'Longitude']

# Selecting only required numerical columns
numerical_columns = df.select_dtypes(include=['number']).drop(columns=columns_to_exclude)

# Create box plots for each numerical column
fig = px.box(numerical_columns, title='Box Plots for Numerical Columns')
fig.show()

In [ ]:
#Removing Outliers from Boxplot

# Calculate the IQR for the 'Unmarried' column
Q1 = df['Unmarried'].quantile(0.25)
Q3 = df['Unmarried'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Remove outliers from the 'Unmarried' column
df = df[(df['Unmarried'] >= lower_bound) & (df['Unmarried'] <= upper_bound)]


In [ ]:
# Create a box plot for the distribution of Unmarried columns
fig = px.box(df, y=["Unmarried"], title='Box Plot of Unmarried Distribution')
fig.show()

### Distribution of Mental Health Based on Gender

In [ ]:
# Create a new DataFrame for male and female counts
gender_counts = df.groupby('Condition')['Male', 'Female'].sum().reset_index()

# Create bar chart of total male and female
fig = px.bar(gender_counts, x='Condition', y=['Male', 'Female'],
             title='Distribution of Mental Health Conditions by Gender',
             labels={'Condition': 'Mental Health Condition', 'value': 'Count', 'variable': 'Gender'},
             color_discrete_map={'Male': 'blue', 'Female': 'orange'},
             barmode='group')

# Show the chart
fig.show()


<ipython-input-38-2b14b682c050>:2: FutureWarning:

Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.



In [ ]:
# Histogram for age distribution
fig = px.histogram(df, x='Age', title='Histogram of Age Distribution', nbins=20)

# Add gap between bars
fig.update_layout(bargap=0.2)  # You can adjust the value of bargap

fig.show()

In [ ]:
# Treemap for hierarchical structure of mental health conditions within different zones
fig = px.treemap(df, path=['Zone', 'Condition'], title='Treemap of Mental Health Conditions within Different Zones')

fig.show()

In [ ]:
df_with_total = df.copy()

# Calculate the total Mental Health Patient for each condition and year
df_with_total["Total"] = df["Male"] + df["Female"]

# Group the data by condition, year, and calculate the sum of the total population
total_by_condition_year = df_with_total.groupby(["Condition", "Year_AD"])["Total"].sum().reset_index()

# Create an interactive line chart using Plotly Express
fig = px.line(total_by_condition_year, x='Year_AD', y='Total', color='Condition',
              labels={'Total': 'Total Mental Health Patient', 'Year_AD': 'Year'},
              title='Total Mental Health Patient Over Time by Condition',
              line_group='Condition', line_dash='Condition')

# Show the plot
fig.show()


In [ ]:
df

District_Name      Zone Ecological_Belt Development_Region  Year_AD  \
1        Taplejung     Mechi        Mountain            Eastern     2012   
2        Taplejung     Mechi        Mountain            Eastern     2012   
3        Taplejung     Mechi        Mountain            Eastern     2012   
4        Taplejung     Mechi        Mountain            Eastern     2012   
5        Taplejung     Mechi        Mountain            Eastern     2012   
...            ...       ...             ...                ...      ...   
2619      Darchula  Mahakali        Mountain        Far-Western     2020   
2620      Darchula  Mahakali        Mountain        Far-Western     2020   
2621      Darchula  Mahakali        Mountain        Far-Western     2020   
2622      Darchula  Mahakali        Mountain        Far-Western     2020   
2624      Darchula  Mahakali        Mountain        Far-Western     2020   

     Condition                            Type  Male  Female  Age  Married  \
1       Severe                       Psychosis    53      30   50       57   
2        Major                         Anxiety    24      32   21       37   
3        Major              Mental retardation    48      46   20       51   
4        Major  Conversive disorder (Hysteria)    49      29   60       45   
5       Severe                      Alcoholism    30      20   27       49   
...        ...                             ...   ...     ...  ...      ...   
2619    Severe                       Psychosis    31      37   60       42   
2620     Minor                         Anxiety    47      41   53       47   
2621    Severe              Mental retardation    18      22   38       24   
2622    Severe  Conversive disorder (Hysteria)    27      30   18        5   
2624    Normal                        Epilepsy    39      30   24       48   

      Unmarried Employment   Latitude  Longitude  
1            26        yes  27.618589  87.856661  
2            19        yes  27.618589  87.856661  
3            43        yes  27.618589  87.856661  
4            33    retired  27.618589  87.856661  
5             1        yes  27.618589  87.856661  
...         ...        ...        ...        ...  
2619         26         no  29.892711  80.741361  
2620         41        yes  29.892711  80.741361  
2621         16         no  29.892711  80.741361  
2622         52         no  29.892711  80.741361  
2624         21        yes  29.892711  80.741361  

[2217 rows x 15 columns]

### Frequency Distribution Based on District Name

In [ ]:
frequent_distribution = df['District_Name'].value_counts()

print("Frequent Distribution of District_Name:")
print(frequent_distribution)

# Identify the district with the highest number of mental health phenomena
highest_mental_health_district = frequent_distribution.idxmax()

print("\nDistrict with the Highest Number of Mental Health Phenomena:", highest_mental_health_district)

Frequent Distribution of District_Name:
Makawanpur       35
Parbat           35
Kavre            35
Nuwakot          35
Rasuwa           35
                 ..
Kanchanpur       20
Dolkha           19
Sankhuwasabha    19
Darchula         18
Baitadi          10
Name: District_Name, Length: 75, dtype: int64

District with the Highest Number of Mental Health Phenomena: Makawanpur


In [ ]:
# Count the occurrences of each district
district_counts = df['District_Name'].value_counts().reset_index()
district_counts.columns = ['District_Name', 'Count']

# Create a bar graph
fig = px.bar(district_counts, x='District_Name', y='Count', title='Distribution of Districts')
fig.show()

### Correlation Matrix

In [ ]:
# Create a correlation matrix
correlation_matrix = df.corr()

# Display the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
            Year_AD      Male    Female       Age   Married  Unmarried  \
Year_AD    1.000000  0.013345  0.014231  0.004705  0.000739   0.015934   
Male       0.013345  1.000000 -0.038723  0.028058  0.048610   0.547720   
Female     0.014231 -0.038723  1.000000  0.013218  0.036764   0.542574   
Age        0.004705  0.028058  0.013218  1.000000  0.122814  -0.051389   
Married    0.000739  0.048610  0.036764  0.122814  1.000000  -0.568159   
Unmarried  0.015934  0.547720  0.542574 -0.051389 -0.568159   1.000000   
Latitude   0.102521 -0.016135 -0.033888  0.021982  0.008360  -0.034812   
Longitude -0.117021  0.049897  0.010394 -0.014946  0.000162   0.035985   

           Latitude  Longitude  
Year_AD    0.102521  -0.117021  
Male      -0.016135   0.049897  
Female    -0.033888   0.010394  
Age        0.021982  -0.014946  
Married    0.008360   0.000162  
Unmarried -0.034812   0.035985  
Latitude   1.000000  -0.842339  
Longitude -0.842339   1.000000  


<ipython-input-45-814630db56e9>:2: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.



In [ ]:
# Create an heatmap of correlation
fig = px.imshow(correlation_matrix, labels=dict(color="Correlation"),
                x=correlation_matrix.index, y=correlation_matrix.columns,
                title='Correlation Heatmap of Mental Health Data', color_continuous_scale='Viridis')

# Show the plot
fig.show()

# Model Training & Testing


1.   Logistic Regression
2.   Random Forest Classifier
3.   Neural Network





In [ ]:
df_encoded = df.copy()

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Encode categorical columns
df_encoded['Condition'] = label_encoder.fit_transform(df['Condition'])
df_encoded['Type'] = label_encoder.fit_transform(df['Type'])
df_encoded['Employment'] = label_encoder.fit_transform(df['Employment'])
df_encoded['District_Name'] = label_encoder.fit_transform(df['District_Name'])
df_encoded['Zone'] = label_encoder.fit_transform(df['Zone'])

In [ ]:
# Features (X) are 'District_Name', 'Zone', 'Type', 'Age', and 'Employment'
X = df_encoded[['District_Name', 'Zone', 'Type', 'Age', 'Employment']]
y = df_encoded['Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features (optional but often recommended for logistic regression)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Logistic Regression

In [ ]:
# Logistic Regression
logistic_model = LogisticRegression()
logistic_model.fit(X_train_scaled, y_train)
logistic_predictions = logistic_model.predict(X_test_scaled)

In [ ]:
# Evaluate models
print("Logistic Regression:")
print("Accuracy:", accuracy_score(y_test, logistic_predictions))
print("F1 Score:", f1_score(y_test, logistic_predictions, average='weighted'))
print("Classification Report:\n", classification_report(y_test, logistic_predictions))


Logistic Regression:
Accuracy: 0.268018018018018
F1 Score: 0.25590534656045677
Classification Report:
               precision    recall  f1-score   support

           0       0.29      0.48      0.36       113
           1       0.24      0.23      0.24       104
           2       0.28      0.20      0.23       111
           3       0.24      0.16      0.19       116

    accuracy                           0.27       444
   macro avg       0.26      0.27      0.26       444
weighted avg       0.26      0.27      0.26       444



In [ ]:

from sklearn.metrics import confusion_matrix

# Create the confusion matrix
confusion_matrix = confusion_matrix(y_test, logistic_predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix)
fig = go.Figure(data=go.Heatmap(
                   z=confusion_matrix,
                   x=['Predicted Negative', 'Predicted Positive'],
                   y=['Actual Negative', 'Actual Positive'],
                   colorscale='Viridis'))

# Update heatmap layout
fig.update_layout(title='Confusion Matrix',
                  xaxis=dict(title='Predicted label'),
                  yaxis=dict(title='True label'))

# Show plot
fig.show()

Confusion Matrix:
[[54 22 15 22]
 [32 24 24 24]
 [47 27 22 15]
 [51 27 19 19]]


## Random Forest

In [ ]:
# Random Forest
random_forest_model = RandomForestClassifier()
random_forest_model.fit(X_train, y_train)
random_forest_predictions = random_forest_model.predict(X_test)

In [ ]:
print("\nRandom Forest:")
print("Accuracy:", accuracy_score(y_test, random_forest_predictions))
# Use 'micro' for balanced data
f1 = f1_score(y_test, random_forest_predictions, average='micro')
print(f'F1-score (SVM): {f1}')
print("Classification Report:\n", classification_report(y_test, random_forest_predictions))



Random Forest:
Accuracy: 0.7184684684684685
F1-score (SVM): 0.7184684684684685
Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.68      0.69       113
           1       0.67      0.71      0.69       104
           2       0.72      0.77      0.75       111
           3       0.77      0.71      0.74       116

    accuracy                           0.72       444
   macro avg       0.72      0.72      0.72       444
weighted avg       0.72      0.72      0.72       444



In [ ]:
from sklearn.metrics import confusion_matrix
# Create the confusion matrix
confusion_matrix = confusion_matrix(y_test, random_forest_predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix)
fig = go.Figure(data=go.Heatmap(
                   z=confusion_matrix,
                   x=['Predicted Negative', 'Predicted Positive'],
                   y=['Actual Negative', 'Actual Positive'],
                   colorscale='Viridis'))

# Update heatmap layout
fig.update_layout(title='Confusion Matrix',
                  xaxis=dict(title='Predicted label'),
                  yaxis=dict(title='True label'))

# Show plot
fig.show()

Confusion Matrix:
[[77 12 11 13]
 [ 9 74 15  6]
 [10 10 86  5]
 [13 14  7 82]]


## Neural Network

In [ ]:
# Neural Network
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train_scaled.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))

model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_data=(X_test_scaled, y_test))


Epoch 1/100
56/56 [==============================] - 1s 6ms/step - loss: 2.0078 - val_loss: 1.3693
Epoch 2/100
56/56 [==============================] - 0s 4ms/step - loss: 1.2991 - val_loss: 1.3265
Epoch 3/100
56/56 [==============================] - 0s 3ms/step - loss: 1.2919 - val_loss: 1.3142
Epoch 4/100
56/56 [==============================] - 0s 3ms/step - loss: 1.2721 - val_loss: 1.2986
Epoch 5/100
56/56 [==============================] - 0s 3ms/step - loss: 1.2595 - val_loss: 1.3065
Epoch 6/100
56/56 [==============================] - 0s 2ms/step - loss: 1.2484 - val_loss: 1.2847
Epoch 7/100
56/56 [==============================] - 0s 3ms/step - loss: 1.2448 - val_loss: 1.2676
Epoch 8/100
56/56 [==============================] - 0s 2ms/step - loss: 1.2347 - val_loss: 1.2731
Epoch 9/100
56/56 [==============================] - 0s 2ms/step - loss: 1.2294 - val_loss: 1.2740
Epoch 10/100
56/56 [==============================] - 0s 3ms/step - loss: 1.2157 - val_loss: 1.2585
Epoch 11/

In [ ]:
# Evaluate Neural Network
nn_predictions = model.predict(X_test_scaled)
nn_mse = mean_squared_error(y_test, nn_predictions)
print(f'Neural Network Mean Squared Error: {nn_mse}')

14/14 [==============================] - 0s 1ms/step
Neural Network Mean Squared Error: 1.0748112415532467


In [ ]:
# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, nn_predictions)
print(f'SVR Mean Absolute Error (MAE): {mae}')

SVR Mean Absolute Error (MAE): 0.8202886236412031


In [ ]:
y_test = y_test.astype(int)
nn_predictions = nn_predictions.astype(int)


In [ ]:
print("Neural Network")
print("Accuracy:", accuracy_score(y_test, nn_predictions))

f1 = f1_score(y_test, nn_predictions, average='micro')  # Use 'micro' for balanced data
print(f'F1-score (SVM): {f1}')

print("Classification Report:\n", classification_report(y_test, nn_predictions))




Neural Network
Accuracy: 0.38738738738738737
F1-score (SVM): 0.38738738738738737
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.52      0.51       113
           1       0.30      0.65      0.42       104
           2       0.39      0.32      0.35       111
           3       0.82      0.08      0.14       116

    accuracy                           0.39       444
   macro avg       0.50      0.39      0.36       444
weighted avg       0.51      0.39      0.35       444



In [ ]:
from sklearn.metrics import confusion_matrix
# Create the confusion matrix
confusion_matrix = confusion_matrix(y_test, nn_predictions)

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix)
fig = go.Figure(data=go.Heatmap(
                   z=confusion_matrix,
                   x=['Predicted Negative', 'Predicted Positive'],
                   y=['Actual Negative', 'Actual Positive'],
                   colorscale='Viridis'))

# Update heatmap layout
fig.update_layout(title='Confusion Matrix',
                  xaxis=dict(title='Predicted label'),
                  yaxis=dict(title='True label'))

# Show plot
fig.show()

Confusion Matrix:
[[59 47  7  0]
 [25 68 10  1]
 [17 57 36  1]
 [16 51 40  9]]
